include(ExternalProject)

set(EXTERNAL_INSTALL_DIR ${PROJECT_BINARY_DIR}/install)
set(EXTERNAL_INCLUDE_DIR ${EXTERNAL_INSTALL_DIR}/include)
set(EXTERNAL_LIBRARY_DIR ${EXTERNAL_INSTALL_DIR}/lib)

ExternalProject_Add(
    dep_glfw
    GIT_REPOSITORY "https://github.com/glfw/glfw.git"
    GIT_TAG "3.3.2"
    GIT_SHALLOW 1
    UPDATE_COMMAND ""
    PATCH_COMMAND ""
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_DIR}
        -DGLFW_BUILD_EXAMPLES=OFF
        -DGLFW_BUILD_TESTS=OFF
        -DGLFW_BUILD_DOCS=OFF
        -DCMAKE_POLICY_VERSION_MINIMUM=3.5
    TEST_COMMAND ""
    )
set(EXTERNAL_PROJECTS ${EXTERNAL_PROJECTS} dep_glfw)
set(EXTERNAL_LIBRARYS ${EXTERNAL_LIBRARYS} glfw3)

ExternalProject_Add(
    dep_glad
    GIT_REPOSITORY "https://github.com/Dav1dde/glad"
    GIT_TAG "v0.1.34"
    GIT_SHALLOW 1
    UPDATE_COMMAND ""
    PATCH_COMMAND ""
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_DIR}
        -DGLAD_INSTALL=ON
        -DCMAKE_POLICY_VERSION_MINIMUM=3.5
    TEST_COMMAND ""
    )
set(EXTERNAL_PROJECTS ${EXTERNAL_PROJECTS} dep_glad)
set(EXTERNAL_LIBRARYS ${EXTERNAL_LIBRARYS} glad)
